361221: View delivery project users
DEFRA/adp-portal pull request #111
Opened 2024-05-10 16:36 UTC by jamescoxheadcapgemini

# **What this PR does / why we need it**:
Adds tab to view project users to entity page. [AB#361221](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/361221)

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
![image](https://github.com/DEFRA/adp-portal/assets/118891549/2b10b826-15cd-4c82-b0ab-bd76ad32f4b8)

# Checklist (please delete before completing or setting auto-complete)
- [x] Story Work items associated (not Tasks)
- [x] Successful testing run(s) link provided
- [x] Title pattern should be `{work item number}: {title}`
- [x] Description covers all the changes in the PR
- [x] This PR contains documentation
- [x] This PR contains tests
- [x] Version number in [package.json](https://github.com/DEFRA/adp-portal/blob/main/app/package.json#L3) has been updated

# Dependency check (tick or delete)
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

- [ ] ADP Software Templates? - https://github.com/DEFRA/adp-software-templates
- [ ] ADP Portal Web API? https://github.com/DEFRA/adp-portal-api

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-05-10 16:40 UTC, jeevankuduvaravindran submitted a review, later dismissed

2024-05-10 16:41 UTC, rajeshkaremane approved these changes

2024-05-10 16:42 UTC, danny-may approved these changes

2024-05-10 16:43 UTC, danny-may requested changes

2024-05-10 16:43 UTC, danny-may commented on app/plugins/adp/src/components/DeliveryProjectUser/DeliveryProjectUserViewPage.tsx
> +          role: 'Delivery Programme Admin',
This should be computed from isTechUser and isAdmin right?

2024-05-10 16:45 UTC, danny-may commented on app/packages/app/src/components/catalog/EntityPage.tsx
> +
Tests for this new route - e.g. https://github.com/DEFRA/adp-portal/blob/aa0a83a71957522978d2de1e422e1f99af5d0295/app/packages/app/src/components/catalog/EntityPage.test.tsx#L378-L380

2024-05-13 11:22 UTC, danny-may approved these changes

2024-05-13 11:24 UTC, merged